### ISSUE TITLE
Store is shared between SSR renders

### ISSUE THREAD

**Issue by TimonVS** [lordgiotto/react-metatags-hook#5]
I'm facing an issue where we're getting unwanted metatags on a page.

A simplified example: say I have two types of pages, a shop index and a product detail page. The shop index page has this code:

```js
useMetaTags({
    title: `Shop Index`
  })
```

And the product detail page has this code:

```js
useMetaTags({
    title: `Product Detail`,
    metas: [
      { name: 'og:title', content: 'Product Title Here' }
    ]
  })
```

Now when I visit just the shop index (rendered by SSR) I'll just get the title. When I visit the product detail page in another tab and then reload the shop index page, I also get the `og:title` tag, even though this is meant for the product detail page only.

I have debugged it a bit and I think the problem is that [`metaStore`](https://github.com/lordgiotto/react-metatags-hook/blob/master/src/state/store.ts#L7) is instantiated once on the server and is shared for all SSR requests. `addMetasToStore` is being called for every page that's handled by SSR and keeps adding objects to `metaStore`.

I think [react-helmet-async](https://github.com/staylor/react-helmet-async) solves this by using context.

**Comment by lordgiotto** [comment]
Hi Timon, sorry for the late reply. I'll have a look into it asap.
Actually I designed this thing exactly the way you're describing (with a lambda SSR in mind), and now I realize the limitations of my approach when it comes to a server that renders components multiple times.
I'll try to find a solution for it :)

**Comment by dmythro** [comment]
Hi, curious about this too, was looking for a hook-based solution for the next project, it has SSR too.

**Comment by ialpert** [comment]
Maybe exposing **clearStore()** would be a solution?

**Comment by lordgiotto** [comment]
Sorry guys, I would have liked to look into this earlier, but I'm having some quite busy months.
Actually @ialpert that's a brilliant idea, thank you, it could solve the problem.

Probably the context solution would be more reliable and easy to use, but it would also be a breaking change, and would require some thought to be done properly.

I can expose a way to clear the store now, and I will explore the context solution in the meantime.

**Comment by lordgiotto** [comment]
Hi @TimonVS, @z-ax and @ialpert.
I just release a new version of the library.
Now you can use the function `resetMetaTags` to clear the meta tags definitions stored in the library: when SSR you can use it before re-rendering the App in order to clear the previous meta tags definitions.

Let me know if this works for you :)

Cheers!
