### ISSUE TITLE
The key generated to map tags doesn't consider multi values attributes (like alternate and og:locale:alternate)

### ISSUE THREAD

**Issue by rntdrts** [lordgiotto/react-metatags-hook#7]
From what I was able to understand you're using the attribute as the key in a Set, the problem with this is that some of the keys can assume multiple values.

I think a quick fix is to add `key` as an attribute so it can iterate and identify different attributes with the same value.

Some examples:
```
<link rel="alternate" content="domain/en/...">
<link rel="alternate" content="domain/pt/...">
...
<meta property="og:locale:alternate" content="pt_PT">
<meta property="og:locale:alternate" content="fr_FR">  
```

**Comment by lordgiotto** [comment]
Hi rntdrts,
sorry for the delay.

I just pushed a new version on NPM. 
Now the `id` attribute is always used to check if a tag is unique or not. If you need to specify two tags with the same attributes, you can just add `id` with a different arbitrary string to prevent it to be overwritten.

Specifically for your issue, if you define the tags this way:
```
useMetaTags({
  links: [
    { rel: 'attribute', content: 'domain/en/...', id: 'link_rel_en'  },
    { rel: 'attribute', content: 'domain/pt/...', id: 'link_rel_pt'  },
  ],
  metas: [
    { property: 'og:locale:alternate', content: 'pt_PT', id: 'og_locale_pt'  },
    { property: 'og:locale:alternate', content: 'fr_FR', id: 'og_locale_fr'  },
  ]
})
```
the output in the dom will be
```
<link rel="alternate" content="domain/en/..." id="link_rel_en" />
<link rel="alternate" content="domain/pt/..." id="link_rel_pt" />
...
<meta property="og:locale:alternate" content="pt_PT" id="og_locale_pt" />
<meta property="og:locale:alternate" content="fr_FR" id="og_locale_fr" />  
```

I hope this fixes your issue :)
Let me know!

**Comment by rntdrts** [comment]
Thank you @lordgiotto! 🙏
